### ISSUE TITLE
Invalid query data sent in product list

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-dashboard#478]
### What I'm trying to achieve
Get the product list.

### Steps to reproduce the problem
1. Go in product list (Catalogue > Product);
2. You should have a popup: "Saleor ran into an unexpected issue".

### What I expected to happen
Not have the popup "Saleor ran into an unexpected issue".

### What happened instead
I get a popup saying "Saleor ran into an unexpected issue", which is resulting from:

#### Query
```yaml
---
'5':
  operationName: GridAttributes
  query: |
    fragment PageInfoFragment on PageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
      __typename
    }

    query GridAttributes($first: Int!, $after: String, $ids: [ID!]!) {
      availableInGrid: attributes(first: $first, after: $after, filter: {availableInGrid: true, isVariantOnly: false}) {
        edges {
          node {
            id
            name
            __typename
          }
          __typename
        }
        pageInfo {
          ...PageInfoFragment
          __typename
        }
        totalCount
        __typename
      }
      grid: attributes(first: 25, filter: {ids: $ids}) {
        edges {
          node {
            id
            name
            __typename
          }
          __typename
        }
        __typename
      }
    }
  variables:
    first: 6
    ids:
    - isPublished
    - price
    - productType
```

#### Response
```yaml
5: 
 errors: 
  - 
   message: "{\"ids\": [{\"message\": \"Invalid ID specified.\", \"code\": \"\"}]}"
   locations: 
    - 
   line: 26
     column: 3
   path: 
    - 
   grid
   extensions: 
    exception: 
     code: GraphQLError
 data: 
  availableInGrid: 
   edges: 
    - 
   node: 
      id: QXR0cmlidXRlOjIx
      name: ABV
      __typename: Attribute
     __typename: AttributeCountableEdge
    - 
   node: 
      id: QXR0cmlidXRlOjE1
      name: "Bottle Size"
      __typename: Attribute
     __typename: AttributeCountableEdge
    - 
   node: 
      id: QXR0cmlidXRlOjE4
      name: "Bucket Size"
      __typename: Attribute
     __typename: AttributeCountableEdge
    - 
   node: 
      id: QXR0cmlidXRlOjE0
      name: Color
      __typename: Attribute
     __typename: AttributeCountableEdge
    - 
   node: 
      id: QXR0cmlidXRlOjIy
      name: "Cushion Size"
      __typename: Attribute
     __typename: AttributeCountableEdge
    - 
   node: 
      id: QXR0cmlidXRlOjE2
      name: Flavor
      __typename: Attribute
     __typename: AttributeCountableEdge
   pageInfo: 
    endCursor: "YXJyYXljb25uZWN0aW9uOjU="
    hasNextPage: true
    hasPreviousPage: false
    startCursor: "YXJyYXljb25uZWN0aW9uOjA="
    __typename: PageInfo
   totalCount: 11
   __typename: AttributeCountableConnection
  grid: null
```

### Versions
Dashboard: [05078112da4b015a243326c54ca341b2e2e1adc3](https://github.com/mirumee/saleor-dashboard/tree/05078112da4b015a243326c54ca341b2e2e1adc3)
Core: [987aff0dd59fbbf8ad00e922ea6a1931102f2372](https://github.com/mirumee/saleor/tree/987aff0dd59fbbf8ad00e922ea6a1931102f2372)
